// <auto-generated />
using System;
using Credence.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Credence.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CredenceDbContext))]
    [Migration("20260223175828_val001")]
    partial class val001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Credence.Domain.AuthContext.Entities.Role", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayRoleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AU_Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new byte[] { 224, 4, 37, 63, 137, 79, 211, 65, 154, 12, 3, 5, 232, 44, 51, 1 },
                            ConcurrencyStamp = "9a7b6c5d-1234-4abc-8def-1a2b3c4d5e6f",
                            DisplayRoleName = "Administrador",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new byte[] { 46, 107, 31, 140, 74, 61, 124, 79, 155, 18, 110, 90, 157, 60, 79, 129 },
                            ConcurrencyStamp = "b7a3c9f4-2e61-4d8b-a5c2-9f3e7a1d6b80",
                            DisplayRoleName = "Two-Factor Pending",
                            Name = "two_factor_pending",
                            NormalizedName = "TWO_FACTOR_PENDING"
                        });
                });

            modelBuilder.Entity("Credence.Domain.AuthContext.Entities.UserCompany", b =>
                {
                    b.Property<byte[]>("UserId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("CompanyId")
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("IsDeletedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.HasKey("UserId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("AU_UserCompanies", (string)null);
                });

            modelBuilder.Entity("Credence.Domain.AuthContext.Entities.UserRole", b =>
                {
                    b.Property<byte[]>("UserId")
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("RoleId")
                        .HasColumnType("BINARY(16)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AU_UserRoles", (string)null);
                });

            modelBuilder.Entity("Credence.Domain.BusinessContext.Entities.Business", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("Id");

                    b.Property<byte[]>("CompanyId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Email");

                    b.Property<DateTime>("IsDeletedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<byte[]>("UserId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("PF_Businesses", (string)null);
                });

            modelBuilder.Entity("Credence.Domain.CompanyContext.Entities.Company", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("Id");

                    b.Property<byte[]>("BusinessId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("CompanyId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Email");

                    b.Property<DateTime>("IsDeletedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<byte[]>("UserId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("PF_Companies", (string)null);
                });

            modelBuilder.Entity("Credence.Domain.ProfileContext.Entities.Address", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("Id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<byte[]>("CompanyId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Complement")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasDefaultValue("Brasil");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Email");

                    b.Property<DateTime>("IsDeletedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<byte[]>("UserId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("UserId");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("PF_Addresses", (string)null);
                });

            modelBuilder.Entity("Credence.Domain.ProfileContext.Entities.Contact", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("Id");

                    b.Property<byte[]>("CompanyId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Email");

                    b.Property<DateTime>("IsDeletedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<byte[]>("UserId")
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("PF_Contacts", (string)null);
                });

            modelBuilder.Entity("Credence.Domain.SalesContext.Entities.Category", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("Id");

                    b.Property<byte[]>("CompanyId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Email");

                    b.Property<DateTime>("IsDeletedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("SA_Categories", (string)null);
                });

            modelBuilder.Entity("Credence.Domain.SalesContext.Transaction", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("Id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("CategoryId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("CompanyId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Email");

                    b.Property<DateTime>("IsDeletedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<DateTime>("PaidOrReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR");

                    b.Property<short>("Type")
                        .HasColumnType("SMALLINT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME(6)");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SA_Transactions", (string)null);
                });

            modelBuilder.Entity("Credence.Domain.UserContext.Entities.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AU_User", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("Id");

                    b.Property<string>("ClaimType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("RoleId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AU_RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)")
                        .HasColumnName("Id");

                    b.Property<string>("ClaimType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AU_UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("BINARY(16)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AU_UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<byte[]>("UserId")
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AU_UserTokens", (string)null);
                });

            modelBuilder.Entity("Credence.Domain.AuthContext.Entities.UserCompany", b =>
                {
                    b.HasOne("Credence.Domain.CompanyContext.Entities.Company", "Company")
                        .WithMany("UserCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Credence.Domain.UserContext.Entities.User", "User")
                        .WithMany("UserCompanies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Credence.Domain.AuthContext.Entities.UserRole", b =>
                {
                    b.HasOne("Credence.Domain.AuthContext.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Credence.Domain.UserContext.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Credence.Domain.BusinessContext.Entities.Business", b =>
                {
                    b.OwnsOne("Credence.Domain.UserContext.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<byte[]>("BusinessId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Name");

                            b1.HasKey("BusinessId");

                            b1.ToTable("PF_Businesses");

                            b1.WithOwner()
                                .HasForeignKey("BusinessId");
                        });

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Credence.Domain.CompanyContext.Entities.Company", b =>
                {
                    b.HasOne("Credence.Domain.BusinessContext.Entities.Business", "Business")
                        .WithMany("Companies")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Credence.Domain.CompanyContext.ValueObjects.CompanyName", "CompanyName", b1 =>
                        {
                            b1.Property<byte[]>("CompanyId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("LegalName");

                            b1.Property<string>("TradeName")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("TradeName");

                            b1.HasKey("CompanyId");

                            b1.ToTable("PF_Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Credence.Domain.CompanyContext.ValueObjects.CompanyStatus", "Status", b1 =>
                        {
                            b1.Property<byte[]>("CompanyId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<sbyte>("IsActive")
                                .HasColumnType("TINYINT")
                                .HasColumnName("IsActive");

                            b1.Property<DateTime>("LastStatusChanged")
                                .HasColumnType("DATETIME(6)")
                                .HasColumnName("LastStatusChanged");

                            b1.HasKey("CompanyId");

                            b1.ToTable("PF_Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("Credence.Domain.SharedContext.ValueObjects.TaxId", "TaxId", b1 =>
                        {
                            b1.Property<byte[]>("CompanyId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<string>("CNPJ")
                                .HasMaxLength(11)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("CNPJ");

                            b1.HasKey("CompanyId");

                            b1.ToTable("PF_Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Business");

                    b.Navigation("CompanyName")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();

                    b.Navigation("TaxId")
                        .IsRequired();
                });

            modelBuilder.Entity("Credence.Domain.ProfileContext.Entities.Address", b =>
                {
                    b.HasOne("Credence.Domain.CompanyContext.Entities.Company", null)
                        .WithOne("Address")
                        .HasForeignKey("Credence.Domain.ProfileContext.Entities.Address", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Credence.Domain.ProfileContext.Entities.Contact", b =>
                {
                    b.HasOne("Credence.Domain.CompanyContext.Entities.Company", null)
                        .WithOne("Contact")
                        .HasForeignKey("Credence.Domain.ProfileContext.Entities.Contact", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Credence.Domain.ProfileContext.Entities.SocialNetwork", "SocialNetworks", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("BIGINT")
                                .HasColumnName("Id");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<byte[]>("ContactId")
                                .IsRequired()
                                .HasColumnType("BINARY(16)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("VARCHAR");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("VARCHAR");

                            b1.HasKey("Id");

                            b1.HasIndex("ContactId");

                            b1.ToTable("PF_SocialNetworks", (string)null);

                            b1.WithOwner("Contact")
                                .HasForeignKey("ContactId");

                            b1.Navigation("Contact");
                        });

                    b.OwnsOne("Credence.Domain.ProfileContext.ValueObjects.WebSite", "WebSite", b1 =>
                        {
                            b1.Property<byte[]>("ContactId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<string>("Url")
                                .HasMaxLength(300)
                                .HasColumnType("varchar(300)")
                                .HasColumnName("WebSite");

                            b1.HasKey("ContactId");

                            b1.ToTable("PF_Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsOne("Credence.Domain.SharedContext.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<byte[]>("ContactId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<string>("Home")
                                .HasMaxLength(11)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Home");

                            b1.Property<string>("Landline")
                                .HasMaxLength(11)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Landline");

                            b1.Property<string>("Mobile")
                                .HasMaxLength(11)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Mobile");

                            b1.Property<string>("Other")
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Other");

                            b1.Property<string>("Skype")
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Skype");

                            b1.Property<string>("Telegram")
                                .HasMaxLength(20)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Telegram");

                            b1.Property<string>("WhatsApp")
                                .HasMaxLength(15)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("WhatsApp");

                            b1.Property<string>("Work")
                                .HasMaxLength(11)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Work");

                            b1.HasKey("ContactId");

                            b1.ToTable("PF_Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("SocialNetworks");

                    b.Navigation("WebSite")
                        .IsRequired();
                });

            modelBuilder.Entity("Credence.Domain.SalesContext.Transaction", b =>
                {
                    b.HasOne("Credence.Domain.SalesContext.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Credence.Domain.UserContext.Entities.User", b =>
                {
                    b.OwnsOne("Credence.Domain.SharedContext.ValueObjects.Age", "Age", b1 =>
                        {
                            b1.Property<byte[]>("UserId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<int>("Value")
                                .HasMaxLength(3)
                                .HasColumnType("INT")
                                .HasColumnName("Age");

                            b1.HasKey("UserId");

                            b1.ToTable("AU_User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Credence.Domain.SharedContext.ValueObjects.Gender", "Gender", b1 =>
                        {
                            b1.Property<byte[]>("UserId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<sbyte>("Value")
                                .HasMaxLength(2)
                                .HasColumnType("TINYINT")
                                .HasColumnName("Gender");

                            b1.HasKey("UserId");

                            b1.ToTable("AU_User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Credence.Domain.SharedContext.ValueObjects.Image", "Image", b1 =>
                        {
                            b1.Property<byte[]>("UserId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("varchar(300)")
                                .HasColumnName("Image");

                            b1.HasKey("UserId");

                            b1.ToTable("AU_User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Credence.Domain.UserContext.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<byte[]>("UserId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("DisplayName");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(180)
                                .HasColumnType("varchar(180)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(180)
                                .HasColumnType("varchar(180)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserId");

                            b1.ToTable("AU_User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Credence.Domain.UserContext.ValueObjects.LoginOptions", "LoginOptions", b1 =>
                        {
                            b1.Property<byte[]>("UserId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<DateTime>("LastLogin")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("LastLogin");

                            b1.HasKey("UserId");

                            b1.ToTable("AU_User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Credence.Domain.UserContext.ValueObjects.PasswordExpire", "PasswordExpire", b1 =>
                        {
                            b1.Property<byte[]>("UserId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<DateTime>("PasswordChangedAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("PasswordChangedAt");

                            b1.HasKey("UserId");

                            b1.ToTable("AU_User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Credence.Domain.UserContext.ValueObjects.TwoFactor", "SendCodeByEmailDisabledAt", b1 =>
                        {
                            b1.Property<byte[]>("UserId")
                                .HasColumnType("BINARY(16)");

                            b1.Property<DateTime>("SendCodeByEmailDisabledAt")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("SendCodeByEmailDisabledAt");

                            b1.HasKey("UserId");

                            b1.ToTable("AU_User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Age");

                    b.Navigation("Gender");

                    b.Navigation("Image");

                    b.Navigation("LoginOptions");

                    b.Navigation("Name");

                    b.Navigation("PasswordExpire");

                    b.Navigation("SendCodeByEmailDisabledAt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Credence.Domain.AuthContext.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Credence.Domain.UserContext.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Credence.Domain.UserContext.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Credence.Domain.UserContext.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Credence.Domain.AuthContext.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Credence.Domain.BusinessContext.Entities.Business", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Credence.Domain.CompanyContext.Entities.Company", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("UserCompanies");
                });

            modelBuilder.Entity("Credence.Domain.UserContext.Entities.User", b =>
                {
                    b.Navigation("UserCompanies");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
